name: Flutter Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  clone_repo:
    runs-on: macOS
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        run: |
          echo "${GITHUB_WORKSPACE}/_flutter/bin" >> ${GITHUB_PATH}

      - name: Install
        run: |
          flutter config --enable-web
          flutter pub get
          
  build_flutter_web:
    needs: clone_repo
    runs-on: macOS
    steps:
      - name: Build
        run: |
          flutter build web

  build_flutter_ios:
    needs: clone_repo
    runs-on: macOS
    steps:
      - name: Build
        run: |
          flutter build ios

  build_flutter_android:
    needs: clone_repo
    runs-on: macOS
    steps:
      - name: Build
        run: |
          flutter build apk --split-per-abi

  build_flutter_macos:
    needs: clone_repo
    runs-on: macOS
    steps:
      - name: Build
        run: |
          flutter build macos

  build_flutter_linux:
    needs: clone_repo
    runs-on: macOS
    steps:
      - name: Build
        run: |
          flutter build linux

